# Generated by Django 4.0.3 on 2022-03-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
