# Generated by Django 4.0.3 on 2022-03-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_system', '0002_remove_appointment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
