# Generated by Django 4.0.3 on 2022-03-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_system', '0003_appointment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
