# Generated by Django 4.0.3 on 2022-03-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_system', '0005_remove_appointment_address_remove_appointment_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='diseae_name',
            new_name='disease_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='doctor',
        ),
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HistoryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='history')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hisotry_files', to='Management_system.history')),
            ],
        ),
    ]
