# Generated by Django 4.0.3 on 2022-03-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_system', '0011_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='of_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Management_system.appointment'),
        ),
    ]
