# Generated by Django 4.0.3 on 2022-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_system', '0012_invoice_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('ESEWA', 'ESEWA'), ('KHALTI', 'KHALTI'), ('STRIPE', 'STRIPE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_stats',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=100, null=True),
        ),
    ]
