# Generated by Django 4.0.3 on 2022-04-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_system', '0013_alter_invoice_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='receipt_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
