# Generated by Django 4.0.3 on 2022-04-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_system', '0015_appointment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
